//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChucVu_NguoiDung
    {
        public int NguoiDung_ID { get; set; }
        public int ChucVu_ID { get; set; }
    
        public virtual ChucVu ChucVu { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
